### ISSUE TITLE
I have a question regarding the plugin

### ISSUE THREAD

**Issue by DimaSergeew** [DavidS-Repo/chunker#2]
can it tick liquids? let's say load physics in chunks? it loads the server quite a lot

**Comment by DavidS-Repo** [comment]
During asynchronous generation, chunks are not actively "ticked." This means processes like liquid flow, crop growth, and other in-game mechanics requiring ticking do not occur until the chunk is fully generated and loaded. Once the chunk is loaded, the API notifies us, allowing us to unload it immediately. Alternatively, we can periodically check the chunk's load level using Bukkit's API for the "TICKING" state and unload the chunk accordingly. This is the method the current code employs. However, I have been testing both approaches and will be posting an update later today featuring a different unloading mechanism.

You can try increasing your `task_queue_timer` to submit tasks less often if you find that the current value is overloading your server. If issues persist, you can test the version being released later today, which should handle a higher rate of task submissions per second. It will also include improved exception handling and a new scheduling system.
